### ISSUE TITLE
/usr/local/rvm/gems/ruby-2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:27:in `rescue in ensure_exists!'

### ISSUE THREAD

**Issue by athreyavc1** [emcvipr/mnrcli#2]
Hi, 

I have installed the mnrcli.rb on the same server which runs VNX MR. 

```
./mnrcli.rb

  EMC M&R on localhost

To list all commands, type 'help'
For help about a specific command, type 'help mycommand'
The list of M&R specific commands is available via 'helpcli'

[1] (Cli)> "parttype=='LUN'".available_properties
Savon::HTTPError: HTTP error (404)
from /usr/local/rvm/gems/ruby-2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:27:in `rescue in ensure_exists!'
```

I access the VNX MR using the link http://<IP>:58080/VNX-MR 

```
cat config.yml
host: localhost
user: admin
password: changeme
```

```
ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

Regards,

A

**Comment by bauagonzo** [comment]
Hello,
What happen if you run : `wget http://localhost:58080/APG-WS/wsapi/db?wsdl` on the local box ?

What version of VNX M&R are you using ?  Just tried on 2 and higher and it works properly.

Btw, if you want to use mnrcli remotely ; in `/opt/VNX/Web-Servers/Tomcat/Default/conf/Catalina/localhost/APG-WS.xml` you can comment out this line : 

`<Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="127.0.0.1" />`

**Comment by athreyavc1** [comment]
Hi, 
I am using 1.1 

```
wget http://localhost:58080/APG-WS/wsapi/db?wsdl
--2016-02-10 04:07:27--  http://localhost:58080/APG-WS/wsapi/db?wsdl
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:58080... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-10 04:07:27 ERROR 404: Not Found.
```

This is the Error I get

**Comment by bauagonzo** [comment]
I'm afraid the Web Service component is packaged with VNX M&R only from 2.x.
mnrcli relies on it so... You will have to upgrade.

Thanks for using mnrcli ;-)
